# Use 'createuser -s postgres' to create a general purpose db (super)user.

development: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DEV_DATABASE']%>
  username: postgres
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: <%= ENV['TEST_DATABASE']%>
  min_messages: warning


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
