default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  host: localhost
  port: 3306

development:
  <<: *default
  database: <%= ENV['DEV_DATABASE']%>

test:
  <<: *default
  database: <%= ENV['TEST_DATABASE']%>

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>